#!/usr/bin/env python3
"""Build and optionally copy only our two assemblies into the isolated clone."""
import argparse
import json
from pathlib import Path
import shutil
import subprocess
import hashlib
import os
import xml.etree.ElementTree as ET
import fcntl
from build_state import source_inputs, record_build, require_deployed_current

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--lab", action="store_true")
    args = parser.parse_args()
    sdk = ROOT / ".work/dotnet/dotnet"
    props = ET.parse(ROOT / "local.props").getroot()
    lock = json.loads((ROOT / "versions.lock.json").read_text())
    expected = lock["sha256"]
    pins = {}
    for name, prop in [("sts2", "GameDataDir"), ("CombatSolver", "SolverDir"), ("HextechRunes", "HextechDir")]:
        directory = props.findtext(f"PropertyGroup/{prop}")
        pins[name] = hashlib.sha256((Path(directory) / f"{name}.dll").read_bytes()).hexdigest()
        if pins[name] != expected[name]:
            raise RuntimeError(f"{name} build dependency changed; refusing to silently replace reviewed pins. "
                               "Review the new binary and update versions.lock.json before building.")
    generated = ROOT / "src/PinnedAssemblies.g.cs"
    contents = ('// Generated by tools/build.py from the actual dependency binaries.\n'
                'namespace HextechSolverCompat;\ninternal static class PinnedAssemblies\n{\n'
                '    internal static readonly System.Collections.Generic.Dictionary<string, string> Hashes = new()\n    {\n' +
                ''.join(f'        ["{name}"] = "{digest}",\n' for name, digest in pins.items()) + '    };\n' +
                '    internal static readonly System.Collections.Generic.Dictionary<string, string> Versions = new()\n    {\n' +
                ''.join(f'        ["{name}"] = {json.dumps(lock[name])},\n' for name in ["CombatSolver", "HextechRunes"]) +
                '    };\n}\n')
    if not generated.exists() or generated.read_text() != contents:
        generated.write_text(contents)
    inputs = source_inputs()
    for project in ["HextechSolverCompat.csproj", "tests/LabMod/HextechCompatLab.csproj"]:
        env = os.environ.copy()
        env.update(DOTNET_CLI_HOME=str(ROOT / ".work/dotnet-home"), DOTNET_CLI_TELEMETRY_OPTOUT="1",
                   DOTNET_GENERATE_ASPNET_CERTIFICATE="false")
        subprocess.run([str(sdk), "build", project, "-c", "Release", "--nologo", "--no-restore",
                        "-p:UseSharedCompilation=false"], cwd=ROOT, env=env, check=True)
    record_build(inputs)
    if args.lab:
        profile_lock = (ROOT / ".local/headless-instances/hextech/fixture.lock").open("w")
        try:
            fcntl.flock(profile_lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            raise RuntimeError("An isolated fixture is running; refusing to replace its DLLs")
        paths = json.loads((ROOT / ".local/headless-instances/hextech/paths.json").read_text())
        mods = Path(paths["mods"])
        if ROOT / ".local/headless-instances/hextech" not in mods.parents:
            raise RuntimeError("Refusing to deploy outside isolated clone")
        for name, folder in [("HextechSolverCompat", ROOT), ("HextechCompatLab", ROOT / "tests/LabMod")]:
            target = mods / name
            target.mkdir(exist_ok=True)
            shutil.copy2(folder / "bin/Release/net9.0" / f"{name}.dll", target)
            shutil.copy2(folder / f"{name}.json", target)
        require_deployed_current(mods)


if __name__ == "__main__":
    main()
