// Generated by tools/build.py from the actual dependency binaries.
namespace HextechSolverCompat;
internal static class PinnedAssemblies
{
    internal static readonly System.Collections.Generic.Dictionary<string, string> Hashes = new()
    {
        ["sts2"] = "9cb4f1ad8c9f284aa8fec3122ffd6d780bbf543d875c817abdd12ff63fbf12b4",
        ["CombatSolver"] = "47b96a372d4f62d65fad1e31c7b1edac73b01b8c29ba02a70c52b8dd9135310c",
        ["HextechRunes"] = "274eebc2513a501fbbb654fc6100d47c6dbba9bf2088137293d234cb6f1ed56f",
    };
    internal static readonly System.Collections.Generic.Dictionary<string, string> Versions = new()
    {
        ["CombatSolver"] = "0.48.1",
        ["HextechRunes"] = "0.9.7",
    };
}
